---

- name: ensure group gkg1648 exists
  group:
      name: gkg1648
      gid: 2012
      state: present
  tags:
    - auth

- name: ensure user gkg1648 exists
  user:
      name: gkg1648
      uid: 2012
      group: gkg1648
      groups: 
        - wheel
      state: present
  tags:
    - auth

- name: ensure gkg1648's SSH key exists
  authorized_key:
      key: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOqE1t4HkiWn/y8dOvbTqofMc8OSo9cMXX4I2Qq7oSDU gkg1648@witr
      user: gkg1648
      state: present
      manage_dir: yes
      exclusive: yes
  tags:
    - auth

