---

- name: ensure group cnl9674 exists
  group:
      name: cnl9674
      gid: 2008
      state: present
  tags:
    - auth

- name: ensure user cnl9674 exists
  user:
      name: cnl9674
      uid: 2008
      group: cnl9674
      groups: 
        - wheel
      state: present
  tags:
    - auth

- name: add cnl9674's SSH key
  authorized_key:
      key: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqzd4AQG/IaTCwBYNCbBLZLMxrukegplFqr5ETD5mkM4xLzrjl0Mj4r5QngwwOKjtAjKJt2shtWCHSFSOyNwE6ne3GeXw4/U4Wm1yXhyzy6LDpha9kfTWA5gwGe58/DcB0y1f4nqeNDt/b6XPv+V4JxpQ9+VsGC1HmIXzFDQmgkLuem7v07oNtiMBdyzX0iIhIK2lecUbxtugJbrtRPbCFcWwy6XnPBKuIAX+Elje8DFJtYzvVaw1fGGLam3cOG4b5nGRsrXeJENcFaK8BcQXx4+qfWRXlj09OWvEjw1Uhs8q5+X1lbyYchHOoRUYqvUhBTNyJ88ARgxm0IDghDw/3gOOa13DCCqClNnOQlb0HvXxsKzQKapyufLW63nZ/AJ3hvRUwEtuzLj6lxbISscE+oZ4Up1whH25WduewISJQRvRymRrRg8NBWmWZUS1CUYhC6BJHlA45Sp3rneXlxYpA6yI5O5dCNDst4xUC9otlPRasFfO+sGeSlF4Tslbs+5SQ1Ea3spwT2NUUpauJV0QXF0I5vlD8lsLPOr54cIC5a0o+4QbhBipDSaS9c1HfEeU+trI4OG9oDGqbgX8zfdMGVYqa+gUdLaJktw1MxT6+f9mby+CspzgIfqHgg/BjmLaN2rXhr1wNtrVEeuiByT2FROeZFjODK1OxtiYIjTxgQw== noah.l98@gmail.com
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/yKLjv4Lvsd+gs3G7auF+qgOdvek87ySanv7i8LIGEACoGSZKfA7ZzwhkRiMpnYV6/VxtrS9QVUHZFaBWZkyE1b5823DPRmQmne9FV1LwJPAyuBqbFqAekPKvJut+aS+Z7QwTNkhk034OnIvo49Uy2cO6dSJPyj3rfz5JaKc0YXIUqasmo2thvsge4EHdXieb6OXoiQ0f3YMkXe/3ufdsMG+Lv2G+XQVVVRnxYcry9WNFEehhpgaMJpJ5k4biSjSwYcy3kDSnHxrRV8KpaLpHKLQphZ71BKpue/CmzwWY0Bd4xp8W2xErjR+0vvbumtgTfFEbhv4CzvmqER34rZFaPug7utn3dXYO82lhdQuwmPfzo1ul2OGnixWCaUk5ZB5leMu9Mp23t1m6MudMFJVk9g+1BCcVmzUAP9BnTjmKHMECFB3CA+PJHIn/tkkA3f80TAxj443Syduf1knhEtBZsy1wKsoYeeOlya9KlBgxwiF+m0l+g4D796J7jUnOZ96pMF2rqJ0qaVdobFQ5ValBp1edohpslL7PKawEEezJb2rUbQbh0tu2FlxVlP2cVb7GBvf264bUtjU7N4pHfNfR1OAerdrb1oewMBEKWrfmPYugh+B6f0HxFVYBBTX9aqtj9LXBaGm9rdtgadbzwXFJPLJbw0u1Ze3vxPEJUODVUw== cardno:000609714722
      user: cnl9674
      state: present
      manage_dir: yes
      exclusive: yes
  tags:
    - auth
