---

- name: "ensure group {{ item.username }} exists"
  group:
    name: "{{ item.username }}"
    gid: "{{ item.user_id }}"
    state: present
  tags:
    - auth

- name: "ensure user {{ item.username }} is locked out"
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.user_id }}"
    group: "{{ item.username }}"
    groups: ""
    expires: 0
    password_lock: yes
    shell: "/usr/bin/false"
    state: present
  tags:
    - auth

- name: "ensure {{ item.username }}'s SSH key does not exist"
  authorized_key:
    key: "{{ lookup('file', item.username+'.pub') }}"
    user: "{{ item.username }}"
    state: absent
    manage_dir: yes
    exclusive: yes
  tags:
    - auth
