---

# Run OS-specific task sets
- import_tasks: openbsd.yml
  when: ansible_facts['os_family']|lower == 'openbsd'

- import_tasks: freebsd.yml
  when: ansible_facts['os_family']|lower == 'freebsd'

- import_tasks: rhel6.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_lsb.major_release|int == 6

- import_tasks: rhel7.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_lsb.major_release|int == 7

# Run OS-independent task sets
- name: install /etc/issue
  template:
      src: issue.{{ ansible_os_family }}.j2
      dest: /etc/issue
      owner: root
      group: wheel
      mode: '0644'
  tags:
    - base

# - name: install standard sshd configuration file
#   template:
#       src: sshd_config.{{ ansible_os_family }}.j2
#       dest: /etc/ssh/sshd_config
#       owner: root
#       group: wheel
#       mode: '0400'
#   tags:
#     - base
