---

# Run OS-specific task sets
- import_tasks: openbsd.yml
  when: ansible_distribution == "OpenBSD"

- import_tasks: freebsd.yml
  when: ansible_distribution == "FreeBSD"

- import_tasks: rhel6.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '6'

- import_tasks: rhel7.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'

# Run OS-independent task sets
- name: install /etc/issue
  template:
      src: issue.{{ ansible_os_family }}.j2
      dest: /etc/issue
      owner: root
      group: wheel
      mode: '0644'
  tags:
    - base

# - name: install standard sshd configuration file
#   template:
#       src: sshd_config.{{ ansible_os_family }}.j2
#       dest: /etc/ssh/sshd_config
#       owner: root
#       group: wheel
#       mode: '0400'
#   tags:
#     - base
