---

- name: configure mail aliases
  notify:
      - newaliases
  template:
      src: aliases.j2
      dest: /etc/mail/aliases
      owner: root
      group: wheel
      mode: '0644'
  tags:
    - base

- name: configure /etc/mail/secrets with root@witr.rit.edu
  copy:
      src: mail_secrets
      dest: /etc/mail/secrets
      owner: root
      group: _smtpd
      mode: '0640'
  tags:
    - base

- name: configure smtpd to send root email using root@witr.rit.edu
  template:
      src: smtpd.conf.j2
      dest: /etc/mail/smtpd.conf
      owner: root
      group: wheel
      mode: '0644'
      backup: yes
      validate: /usr/sbin/smtpd -nf %s
  tags:
    - base

- name: ensure that there's no .forward file in root's home folder
  file:
      state: absent
      path: /root/.forward
  tags:
    - base

- name: configure doas to permit wheel as root (and root as root)
  copy:
      src: doas.conf
      dest: /etc/doas.conf
      owner: root
      group: wheel
      mode: '0644'
      backup: yes
      validate: /usr/bin/doas -C %s
  tags:
    - base
