---
# Automatically deploy acme-client

# Note that this role does not support generating certificates that need to be
# shared across machines.  It can only generate a certificate that will be used
# on a single machine.  If you try to run this role to generate a shared
# certificate, all but the last one generated will be invalid, and if you
# generate more than three, LetsEncrypt will throttle you.

- name: copy in an httpd configuration just for setting up LetsEncrypt
  template:
    src: httpd-le-standalone.conf.j2
    dest: /etc/httpd.conf
    owner: root
    mode: 0644
    validate: /usr/sbin/httpd -nf %s
  register: httpd_le
  tags:
    - letsencrypt

# Why not a handler?  Handlers are coalesced to the end, but this needs to run
# now (if at all).
- name: reload httpd to enable the new configuration (if necessary)
  service:
    name: httpd
    state: reloaded
  when: "httpd_le.changed" # noqa 503
  tags:
    - letsencrypt

- name: back up the current pf configuration before changing it
  # Is this resiliant to stupidity? No, but we're a pretty small operation so it
  # should be fine for now. Replace with a more unique filename if we start
  # automatically running Ansible playbooks.
  command: cp /etc/pf.conf /etc/pf.conf.ansible-backup
  tags:
    - letsencrypt

# This doesn't use a handler because handlers only run once at the end, and we
# need it to take effect now in order to successfully obtain the certificates.
- name: copy in a pf configuration just for setting up LetsEncrypt
  template:
    src: pf-le-standalone.conf.j2
    dest: /etc/pf.conf
    owner: root
    mode: 0600
    validate: /sbin/pfctl -nf %s
    # Also backup here so that if you break the ansible role, you don't lose the
    # original configuration file on the second run
    backup: yes
  register: pf_le
  tags:
    - letsencrypt

# Why not a handler? Handlers are coalesced to the end, but this needs to run
# now (if at all).
- name: reload pf to enable new rules (if necessary)
  command: pfctl -f /etc/pf.conf
  when: "pf_le.changed" # noqa 503
  register: pf_reload
  tags:
    - letsencrypt

- name: copy in an acme-client configuration for this machine
  template:
    src: acme-client.conf.j2
    dest: /etc/acme-client.conf
    owner: root
    mode: 0644
  tags:
    - letsencrypt

- name: call acme-client
  # re-enable this line once you've fixed our bad naming system
  # command: "/usr/sbin/acme-client -AD {{ tls_cname }}.witr.rit.edu"
  command: "/usr/sbin/acme-client -AD {{ ansible_hostname }}.rit.edu"
  register: acme_result
  failed_when: "acme_result.rc != 0 and acme_result.rc != 2"
  changed_when: "acme_result.rc == 0"
  tags:
    - letsencrypt
  notify:
    - restart httpd

- name: ensure there is a cron entry to renew the certificate
  cron:
    name: "acme-client automatic renewal"
    minute: "45"
    hour: "1"
    job: "sleep $((RANDOM \\% 2048)) && acme-client {{ ansible_hostname }}.rit.edu && rcctl reload httpd"
  tags:
    - letsencrypt

- name: restore the backed-up pf configuration
  command: mv /etc/pf.conf.ansible-backup /etc/pf.conf
  tags:
    - letsencrypt

# Why not a handler?  Consistency.
- name: reload pf to restore backed-up configuration
  command: pfctl -f /etc/pf.conf
  when: "pf_reload.changed" # noqa 503
  tags:
    - letsencrypt
